name: Build and Deploy

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build:
    name: Build Package
    runs-on: ubuntu-latest
    steps:
     - name: Checkout Repository
       uses: actions/checkout@v4

     - name: Set up .NET
       uses: actions/setup-dotnet@v4
       with:
         dotnet-version: |
            6.0.x
            8.0.x

     - name: Build
       run: dotnet build --configuration Release

     - name: Package
       run: >
         dotnet pack --no-restore --no-build --configuration Release
         -p:PackageVersion=${{ github.ref_name }} --output .
         
     - name: Publish
       run: >
        dotnet nuget push /home/runner/work/QueryCraft/QueryCraft/QueryCraft.${{ github.ref_name }}.nupkg
        -s https://nuget.pkg.github.com/lordoleksiy/index.json
        -k ${{ secrets.NUGET_AUTH_TOKEN }}

